[package]
name = "host"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
cap-std = { workspace = true }
wasmtime = { git = "https://github.com/bytecodealliance/wasmtime", rev = "299131ae2d6655c49138bfab2c4469650763ef3b", features = ["component-model"] }
wasi-common = { path = "../wasi-common" }
wasi-cap-std-sync = { path = "../wasi-common/cap-std-sync" }
clap = { version = "4.1.9", features = ["derive"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["env-filter", "fmt" ]}

[dev-dependencies]
test-programs-macros = { path = "../test-programs/macros" }
test-log = { version = "0.2", default-features = false, features = ["trace"] }
tempfile = "3.3.0"
lazy_static = "1"
