# The adapter module created in this repository can technically be either
# compiled for wasm32-wasi or the unknown-unknown target but the unknown version
# is used to be able to specify custom flags here. That way the wasi tests don't
# use these custom flags but the adapter does.
[target.wasm32-unknown-unknown]
rustflags = [
  # Currently all locations that will run this adapter have this feature enabled
  # and this avoid generating a `memcpy` function in the adapter itself.
  '-Ctarget-feature=+bulk-memory',
]
