# The adapter module created in this repository can technically be either
# compiled for wasm32-wasi or the unknown-unknown target but the unknown version
# is used to be able to specify custom flags here. That way the wasi tests don't
# use these custom flags but the adapter does.
[target.wasm32-unknown-unknown]
rustflags = [
  # The adapter must import its memory from the main module so pass this for LLD
  # to generate the right memory import.
  '-Clink-arg=--import-memory',
  # The adapter will allocate its own stack and doesn't use the --stack-first
  # layout that LLD has by default. Set the stack size from LLD to zero here to
  # ensure that the memory imported into the module has a minimum size of 0 as
  # opposed to 1MB which might not be compatible with some WASI-using modules.
  '-Clink-arg=-zstack-size=0',
  # Currently all locations that will run this adapter have this feature enabled
  # and this avoid generating a `memcpy` function in the adapter itself.
  '-Ctarget-feature=+bulk-memory',
]
