[package]
name = "wasi-bindings"
version.workspace = true
edition.workspace = true

[dependencies]
wit-bindgen = { version = "0.3.0", default-features = false, features = ["macros", "realloc"] }

[lib]
crate-type = ["lib"]
